### ISSUE TITLE
wicked does not inform the user that it ignores static routes when configured with dhcp

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/wicked#930]
As documented at  https://bugzilla.opensuse.org/show_bug.cgi?id=1202658, wicket ignores static routes when configured with dhcp, but it does not inform the user of this condition, neither when adding static routes nor when starting the service. Since this can be done with networkmanager, for example, this is unexpected behavior, which costs a lot of time to investigate.

**Comment by mtomaschewski** [comment]
On interfaces configured with dhcp, the dhcp server provides the routes.

As described in [FAQ](https://github.com/openSUSE/wicked/wiki/FAQ/#q-why-wicked-does-not-set-my-default-static-route) and already commented in [boo#1202658](https://bugzilla.opensuse.org/show_bug.cgi?id=1202658), static routes can be applied while the  setup is done via dhcp, but static settings/routes are independent of dhcp and have to be complete by  themself, e.g. in order to apply a route via  gateway, you need to create a direct route entry for the gateway itself (-> [FAQ](https://github.com/openSUSE/wicked/wiki/FAQ/#q-why-wicked-does-not-set-my-default-static-route)).
